/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_choi_knocktalk_NDKAdapter */

#ifndef _Included_com_example_choi_knocktalk_NDKAdapter
#define _Included_com_example_choi_knocktalk_NDKAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_choi_knocktalk_NDKAdapter
 * Method:    setDataSource
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_choi_knocktalk_NDKAdapter_setDataSource
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_choi_knocktalk_NDKAdapter
 * Method:    play
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_example_choi_knocktalk_NDKAdapter_play
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
